from pathlib import Path
import re

path = Path('/home/ubuntu/svg-icon-stylizer/client/src/pages/Home.tsx')
text = path.read_text()
pattern = re.compile(r'            <div className="parameter-group scene-assets">.*?\n          </>', re.S)
replacement = '''            <div className="parameter-group scene-assets"><div className="group-title"><Clapperboard size={15}/><span>默认场景套件</span></div><p>底座保持统一；点缀与围绕装饰可分别选择预设或上传自定义素材。自定义资源会显示在对应场景位置。</p><div className="scene-kit-group"><span>点缀装饰</span><div className="scene-kit-options scene-kit-options-four"><button onClick={() => updateParam("sceneObjectDecor", "none")} className={params.sceneObjectDecor === "none" ? "scene-kit-active" : ""}>无</button><button onClick={() => updateParam("sceneObjectDecor", "orb")} className={params.sceneObjectDecor === "orb" ? "scene-kit-active" : ""}>玻璃球</button><button onClick={() => updateParam("sceneObjectDecor", "cube")} className={params.sceneObjectDecor === "cube" ? "scene-kit-active" : ""}>方块</button><button onClick={() => objectCustomInput.current?.click()} className={params.sceneObjectDecor === "custom" ? "scene-kit-active scene-kit-upload" : "scene-kit-upload"} aria-label="上传自定义点缀装饰"><Upload size={13}/><span>自定义</span></button></div></div><SliderField label="点缀高度" value={params.sceneObjectHeight} min={-90} max={90} suffix=" px" onChange={(value) => updateParam("sceneObjectHeight", value)} /><div className="scene-kit-group"><span>围绕装饰</span><div className="scene-kit-options scene-kit-options-four"><button onClick={() => updateParam("sceneMotionDecor", "none")} className={params.sceneMotionDecor === "none" ? "scene-kit-active" : ""}>无</button><button onClick={() => updateParam("sceneMotionDecor", "ribbon")} className={params.sceneMotionDecor === "ribbon" ? "scene-kit-active" : ""}>飘带</button><button onClick={() => updateParam("sceneMotionDecor", "orbit")} className={params.sceneMotionDecor === "orbit" ? "scene-kit-active" : ""}>环绕</button><button onClick={() => motionCustomInput.current?.click()} className={params.sceneMotionDecor === "custom" ? "scene-kit-active scene-kit-upload" : "scene-kit-upload"} aria-label="上传自定义围绕装饰"><Upload size={13}/><span>自定义</span></button></div></div><SliderField label="围绕高度" value={params.sceneMotionHeight} min={-90} max={90} suffix=" px" onChange={(value) => updateParam("sceneMotionHeight", value)} /><input ref={objectCustomInput} className="visually-hidden" type="file" accept="image/svg+xml,image/png" onChange={(event) => readSceneAsset(event, "sceneObjectCustom")} /><input ref={motionCustomInput} className="visually-hidden" type="file" accept="image/svg+xml,image/png" onChange={(event) => readSceneAsset(event, "sceneMotionCustom")} /></div>
          </>'''
updated, count = pattern.subn(replacement, text, count=1)
if count != 1:
    raise SystemExit(f'expected one scene asset block, found {count}')
path.write_text(updated)
